export { createViewBridge, createBoundViewBridge, diffText } from './bridge.js'
export type { ViewBridgeConfig, ViewBridgeHandle, BoundViewBridgeHandle, ApplyTextOptions, ApplyTextResult } from './bridge.js'
export type { Serialize, Parse, Normalize, OnError, ErrorCode, ErrorEvent, IncrementalParse, IncrementalParseResult, TextDiff, CursorMapWriter, SerializeWithMap, Matcher, MatchResult, MatchRun } from './types.js'
export { buildCursorMap, createCursorMapWriter, cursorMapLookup, reverseCursorMapLookup, wrapSerialize } from './cursor-map.js'
export type { TextSegment, CursorMap } from './cursor-map.js'
