export { createViewBridge, createBoundViewBridge, diffText } from './bridge.js'
export type { ViewBridgeConfig, ViewBridgeHandle, BoundViewBridgeHandle, ApplyTextOptions, ApplyTextResult } from './bridge.js'
export type { Serialize, Parse, Normalize, OnError, ErrorCode, ErrorEvent, IncrementalParse, IncrementalParseResult, TextDiff } from './types.js'
export { buildCursorMap, cursorMapLookup, reverseCursorMapLookup } from './cursor-map.js'
export type { TextSegment, CursorMap, LocateText, LocateTextContext } from './cursor-map.js'
